version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://<host>:<port>/<dbname>
      - SPRING_DATASOURCE_USERNAME=<username>
      - SPRING_DATASOURCE_PASSWORD=<password>
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: <dbname>
      POSTGRES_USER: <username>
      POSTGRES_PASSWORD: <password>
    ports:
      - "5432:5432"
