version: '3.8'
services:
  database:
    image: postgres:15
    container_name: stylo_store_db
    environment:
      POSTGRES_DB: stylo_store_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stylo_store_backend
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/stylo_store_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: user123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    links:
      - database

volumes:
  postgres_data:
    driver: local
